### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by the-greeks** [trianglman/sqrl#18]
Hello Sir,

I am trying to implement SQRL on Ubuntu Server, but when I try to open your example webpage nothing loads. Can you please let me know under which directory each file and directory should be located?

Thank you in advance!

**Comment by mjmunger** [comment]
/var/www/html/

File needs to be owned by www-data to execute.

I assume you're using apache... and PHP?

Michael Munger, dCAP, MCPS, MCNPS, MBSS
High Powered Help, Inc.
Microsoft Certified Professional
Microsoft Certified Small Business Specialist
Digium Certified Asterisk Professional
michael@highpoweredhelp.com <mailto:michael@highpoweredhelp.com>

**Comment by the-greeks** [comment]
That's correct Sir. I am using apache and PHP, all the projectbase folder is located in /var/www/html  and owned by www-data but when I am trying to load the page a blank page appears.

**Comment by mjmunger** [comment]
Post your apache conf files.

Michael Munger, dCAP, MCPS, MCNPS, MBSS
High Powered Help, Inc.
Microsoft Certified Professional
Microsoft Certified Small Business Specialist
Digium Certified Asterisk Professional
michael@highpoweredhelp.com <mailto:michael@highpoweredhelp.com>

**Comment by the-greeks** [comment]
More sites (drupal & joomla) are hosted on this web server in /var/www/html but they load correctly. So there shouldn't be a problem with apache. The whole projectbase should be under /var/www/html or some of the projectbase folders should be located in a different folder? I downloaded directly the source code in /var/www/html/projectbase.

**Comment by mjmunger** [comment]
Without code and confs, I can't help you.

Michael Munger, dCAP, MCPS, MCNPS, MBSS
High Powered Help, Inc.
Microsoft Certified Professional
Microsoft Certified Small Business Specialist
Digium Certified Asterisk Professional
michael@highpoweredhelp.com <mailto:michael@highpoweredhelp.com>

**Comment by rwese** [comment]
could this be closed @the-greeks, it is a local issue as said before, I hope you managed to get it setup.

please close this issue.
