### ISSUE TITLE
Replaced vuk,suk with suk,vuk

### ISSUE THREAD

**Issue by Ralle** [trianglman/sqrl#19]
Still new to SQRL so I might be wrong. But from reading the code, this looks confusing.

https://github.com/trianglman/sqrl/blob/425d2f8b4ffd319408d6acf02a44b58a2531bafd/examples/server/includes/ExampleStatefulStorage.php#L69

```    public function createIdentity($key, $suk, $vuk) 
    {
        $sql = "INSERT INTO sqrl_pubkey (public_key,vuk,suk) VALUES (?,?,?)";
        $stmt = $this->conn->prepare($sql);
        $stmt->execute(array($key,$suk,$vuk));
    }
```

**Comment by rwese** [comment]
@Ralle you are not wrong, it is confusing and there is actually an **error in the order the arguments are bound**.

    public_key, vuk,       suk
    $key,       $suk,      $vuk

other than that, the variable named could be more verbose but the function is only 4 lines so no biggy.

**Comment by rwese** [comment]
@Ralle can be closed now
